export enum ErrorCode {
  INVALID_INPUT = "INVALID_INPUT",
  INVALID_API_KEY = "INVALID_API_KEY",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  VALIDATION = "VALIDATION_ERROR",
  DUPLICATE_SLUG = "DUPLICATE_SLUG",
  DATABASE = "DATABASE_ERROR",
  INTERNAL = "INTERNAL_ERROR",
  UNKNOWN = "UNKNOWN",
  // CMS-specific error codes
  ARTICLE_NOT_FOUND = "ARTICLE_NOT_FOUND",
  ARTICLE_EXISTS = "ARTICLE_EXISTS",
  SITE_NOT_FOUND = "SITE_NOT_FOUND",
  // Image upload error codes
  INVALID_ADMIN_KEY = "INVALID_ADMIN_KEY",
  INVALID_FILE_TYPE = "INVALID_FILE_TYPE",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  UPLOAD_FAILED = "UPLOAD_FAILED",
  MISSING_FILE = "MISSING_FILE",
}
