export enum ErrorCode {
  INVALID_INPUT = "INVALID_INPUT",
  INVALID_API_KEY = "INVALID_API_KEY",
  INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  VALIDATION = "VALIDATION_ERROR",
  DUPLICATE_SLUG = "DUPLICATE_SLUG",
  DATABASE = "DATABASE_ERROR",
  INTERNAL = "INTERNAL_ERROR",
  UNKNOWN = "UNKNOWN",
}
